# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: ["--maxkb=1500"]
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-aws-credentials
  - id: detect-private-key
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ["--config", "pyproject.toml"]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files", "--skip", "alembic"]
- repo: https://github.com/pycqa/flake8
  rev: "3.9.2"
  hooks:
  - id: flake8
    args: ["--max-line-length=119", "--extend-ignore=E203"]
    exclude: "^(alembic|.circleci|docs)/.*$"
- repo: https://github.com/pycqa/bandit
  rev: "1.7.0"
  hooks:
  - id: bandit
    args: ["-r", "-ll", "-ii"]
