"""Initial

Revision ID: 127a58bfa903
Revises:
Create Date: 2022-11-16 17:51:24.724808

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "127a58bfa903"
down_revision = None
branch_labels = ("default",)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shortened_link",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("default_parameter", sa.String(), nullable=True),
        sa.Column("redirect_to", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shortened_link")
    # ### end Alembic commands ###
