"""Add clicker

Revision ID: af296672fac5
Revises: 789dfd6427c6
Create Date: 2023-06-19 11:06:14.119316

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "af296672fac5"
down_revision = "789dfd6427c6"
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shortened_link_click", sa.Column("clicker", postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shortened_link_click", "clicker")
    # ### end Alembic commands ###
